version: "3"
dotenv:
  - .env

tasks:
  gband: open test.midi
  midi: timidity test.midi
  test: poetry run pytest {{.update_goldens}} -vvv -s --cov jet_jammer --cov-report=xml --junit-xml report_unit.xml --cov-report html:.cov_html --cov-fail-under 99 {{.CLI_ARGS}}
  update-goldens:
    cmds:
      - task: test
        vars:
          update_goldens: --update-goldens
  fmt:
    cmds:
      - task: isort
      - task: autoflake
      - task: black
  isort: poetry run isort .
  autoflake: poetry run autoflake --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables *.py
  black: poetry run black .
  isort-lint: poetry run isort --check -vvv .
  autoflake-lint: poetry run autoflake -vvv --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables --check *.py
  black-lint: poetry run black --check -vvv .
  lint:
    cmds:
      - task: isort-lint
      - task: autoflake-lint
      - task: black-lint
  flint:
    cmds:
      - task: fmt
      - task: lint
  serve: docker-compose up --remove-orphans --build
  cov: open .cov_html/index.html
  deploy: gcloud run deploy --source .
  serve-local: poetry run uvicorn jet_jammer:app --reload
