version: "3"
dotenv:
  - .env

tasks:
  midi: open test.midi
  test: poetry run pytest -vvv --cov jet_jammer --cov-report=xml --junit-xml report_unit.xml --cov-report html:.cov_html --cov-fail-under 99
  fmt:
    cmds:
      - task: isort
      - task: autoflake
      - task: black
  isort: poetry run isort .
  autoflake: poetry run autoflake --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables .
  black: poetry run black .
  isort-lint: poetry run isort --check .
  autoflake-lint: poetry run autoflake --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables --check .
  black-lint: poetry run black --check .
  lint:
    cmds:
      # - task: isort-lint
      - task: autoflake-lint
      - task: black-lint
  flint:
    cmds:
      - task: fmt
      - task: lint
