name: Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Make a release"
        required: true
        default: "yes"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Semantic Release
        run: |
          pip install python-semantic-release
          semantic-release publish
