name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ hashFiles('poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Poetry install
        run: poetry install
      - name: Black
        run: poetry run black --check .
      - name: autoflake
        run: poetry run autoflake --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables --check .
      - name: Pytest
        run: poetry run pytest -vvv --cov ./ --cov-report=xml --junit-xml report_unit.xml --cov-report html:.cov_html
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "report_unit.xml"
      - name: Archive midi
        uses: actions/upload-artifact@v2
        with:
          name: test-midi
          path: test.midi
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: .cov_html
      - name: Publish
        run: poetry publish --build
