name: CI
on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.8]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry install
        run: poetry install
      - name: Black
        run: poetry run black --check .
      - name: Pytest
        run: poetry run pytest -vvv --cov ./ --cov-report=xml --junit-xml report_unit.xml --cov-report html:.cov_html
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "report_unit.xml"
      - name: Archive midi
        uses: actions/upload-artifact@v2
        with:
          name: test-midi
          path: test.midi
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: .cov_html
